name: Scheduled and Push Tests

on:
  schedule:
    - cron: '10 13 * * *'  # Запуск в 13:10 UTC каждый день
  push:
    branches:
      - main  # Запуск при push в ветку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновленная версия

      - name: Set up Java
        uses: actions/setup-java@v4  # Обновленная версия
        with:
          java-version: '11'  # Задайте версию Java
          distribution: 'temurin'  # Укажите дистрибуцию Java

      - name: Install dependencies
        run: |
          mvn install  # Установить зависимости

      - name: Run tests
        run: |
          mvn test -DsuiteXmlFiles=runner.xml  # Запустить тесты с использованием runner.xml

